version: '3.8'

services:
 
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
      MYSQL_DATABASE: libreria
    ports:
      - "3307:3306"
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 5s
     timeout: 5s
     retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

 
  redis:
    image: redis:alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"


  backend:
    build: .
    container_name: backend-contenedor
    ports:
      - "8080:8080"
    environment:
     SPRING_PROFILES_ACTIVE: docker
     SPRING_DATA_REDIS_HOST: redis  
     SPRING_MAIL_HOST: smtp.gmail.com
     SPRING_MAIL_PORT: 587	 
     CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
     CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
     CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
     MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy 
      redis:
        condition: service_started

volumes:
  mysql_data: