
spring.application.name=biblioteca-api



spring.datasource.url=jdbc:mysql://db:3306/libreria?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tomas.barone.dev@gmail.com
spring.mail.password=${MAIL_PASSWORD:sin_configurar}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.redis.time-to-live=600000

app.cors.allowed-origins=http://localhost:5173